mode: normal
acme_root: seclab
ca_hostname: cert
ca_cert_src: /usr/local/share/ca-certificates/seclab.crt
ca_cert_dest: /etc/caddy/ca.crt
domain: sec.lab
caddy_hostname: "{{ ansible_facts['nodename'] }}"
log_path: /var/log/caddy
webroot: /var/www/html
php_version: "8.3"
proxy_port: 8000
